pipelines:
  speaker_test:
    - audiotestsrc wave=5 volume=0.3 
    - audioconvert 
    - autoaudiosink
  mic_test:
    - alsasrc device=hw:3,0 
    - audioconvert 
    - audioresample 
    - capsfilter caps="audio/x-raw,format=S16LE,channels=1,rate=16000" 
    - autoaudiosink