pipelines:
  speaker_test:
    - audiotestsrc wave=5 volume=0.3 
    - audioconvert 
    - autoaudiosink
  mic_test:
    - alsasrc device=hw:3,0 
    - audioconvert 
    - audioresample 
    - capsfilter caps="audio/x-raw,format=S16LE,channels=1,rate=16000" 
    - autoaudiosink
  wav_scope_test:
    - audiotestsrc 
    - audioconvert 
    - wavescope 
    - glimagesink
  wav_scope_to_rtmp:
    - alsasrc device=hw:3,0 
    - audioconvert 
    - wavescope 
    - queue 
    - videoconvert 
    - x264enc 
    - flvmux streamable=true 
    - queue
    - rtmpsink location="rtmp://localhost:1935/live/wavetest"
  play_pcm:
    - filesrc location=material/16k16bit.pcm
    - capsfilter caps="audio/x-raw,format=S16LE,channels=1,rate=16000,layout=interleaved"
    - audioconvert 
    - audioresample 
    - autoaudiosink

  record_wav:
    - osxaudiosrc
    - audioconvert 
    - audioresample
    - capsfilter caps="audio/x-raw,format=S16LE,channels=1,rate=16000,layout=interleaved"
    - tee
    - queue
    - splitmuxsink location=test_%5d.wav muxer=wavenc
    - tee
    - queue
    - wavescope
    - videoconvert
    - autovideosink