general:
  default_pipeline: pipeline_test
  log_folder: ./log
  log_name: pipeline_verify
  # log level - 0:trace, 1: debug, 2: info ...
  log_level: 2
  # gstreamer log level - GST_LEVEL_FIXME=3,GST_LEVEL_INFO=4,..
  debug_threshold: 3
  http_enabled: 1
  http_port: 9090
  web_root: ./doc
  web_token: GstPipeVerifier
pipelines:
  video_test:
    tags: video, test
    desc: display test video
    steps:
      - videotestsrc num-buffers=100
      - capsfilter caps="video/x-raw, width=1280, height=720, framerate=30/1"
      - timeoverlay
      - identity
      - autovideosink

  mic_test:
    tags: audio, test
    desc: play audio from mic
    steps:
      - autoaudiosrc
      - audioconvert
      - wavescope
      - videoconvert
      - autovideosink

  rtmp_test:
    tags: video, rtmp
    desc: push video to rtmp server
    steps:
      - filesrc location=material/talk.mp4
      - decodebin
      - videoconvert
      - x264enc
      - videoconvert
      - flvmux streamable=true
      - rtmpsink location='rtmp://192.168.104.37:1935/live/talktest'

  mp4_play:
    tags: video, mp4
    desc: playback mp4 video file
    steps:
      - filesrc location=./material/talk.mp4
      - decodebin name=dec
      - videoconvert
      - timeoverlay
      - autovideosink dec.
      - audioconvert
      - audioresample
      - autoaudiosink

  videojpg2rtmp:
    tags: video, rtmp
    desc: push camera video to rtmp server
    steps:
      - v4l2src device=/dev/video1
      - capsfilter caps="image/jpeg,width=1920, height=1080, framerate=30/1"
      - nvv4l2decoder mjpeg=1
      - nvvideoconvert
      - videorate max-rate=30
      - nvv4l2h264enc
      - h264parse
      - flvmux streamable=true
      - rtmpsink location=rtmp://localhost:1935/live/video_test

  videoxraw2rtmp:
    tags: video, rtmp
    desc: push hdmi video to rtmp server
    steps:
      - v4l2src device=/dev/video0
      - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
      - nvvideoconvert
      - videorate max-rate=30
      - nvv4l2h264enc
      - h264parse
      - flvmux streamable=true
      - rtmpsink location=rtmp://localhost:1935/live/video_test

  audio2rtmp:
    tags: video, audio, rtmp
    desc: push audio wavscope video to rtmp server
    steps:
      - alsasrc device=hw:2,0
      - audioconvert
      - wavescope
      - queue
      - videoconvert
      - x264enc
      - flvmux streamable=true
      - queue
      - rtmpsink location="rtmp://localhost:1935/live/audio_test"
# refer to https://gstreamer.freedesktop.org/documentation/additional/design/probes.html
probes:
  mp4_play_probe:
    probe_pipeline: mp4_play
    probe_element: timeoverlay
    probe_pad: src
    #GST_PAD_PROBE_TYPE_ALL_BOTH (1776) – probe buffers
    probe_type: 1776
    probe_callback: probe_pad_callback

  video_test_probe:
    probe_pipeline: video_test
    probe_element: timeoverlay
    probe_pad: src
    probe_type: 1776
    probe_callback: probe_pad_callback

  rtmp_test_probe:
    probe_pipeline: rtmp_test
    probe_element: rtmpsink
    probe_pad: sink
    probe_type: 1776
    probe_callback: probe_meta_data

props:
  rtmp_test_0:
    pipeline_name: rtmp_test
    element_name: rtmpsink
    prop_name: location
    prop_value: rtmp://www.fanyamin.com:1935/live/audio_test
