general:
  default_pipeline: pipeline_test
  log_folder: ./log
  log_name: pipeline_verify
  log_level: 1 # 0:trace, 1: debug, 2: info ...

pipelines:
  pipeline_test:
    - videotestsrc num-buffers=100
    - capsfilter caps="video/x-raw, width=1920, height=1080, framerate=30/1"
    - autovideosink

  mic_test:
    - autoaudiosrc
    - audioconvert
    - wavescope
    - videoconvert
    - autovideosink  

  mac_capture_screen:
    - avfvideosrc capture-screen=true 
    - videoscale 
    - videoconvert 
    - capsfilter caps="video/x-raw,width=640,height=480"
    - osxvideosink

  rtmp_test:    
    - filesrc location=material/talk.mp4
    - decodebin
    - videoconvert 
    - identity drop-allocation=1
    - openh264enc bitrate=4000000
    - videoconvert
    - flvmux streamable=true
    - rtmpsink location='rtmp://192.168.104.199:1935/live/talktest'

  mp4_play:
    - filesrc location=./material/talk.mp4 
    - decodebin name=dec
    - videoconvert 
    - clockoverlay 
    - autovideosink dec. 
    - audioconvert 
    - audioresample 
    - autoaudiosink

  video2rtmp:
    - v4l2src device=/dev/video0
    - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
    - nvvideoconvert
    - videorate max-rate=30
    - nvv4l2h264enc
    - h264parse
    - flvmux streamable=true
    - rtmpsink location=rtmp://localhost:1935/live/video_test

  audio2rtmp:
    - alsasrc device=hw:3,0 
    - audioconvert 
    - wavescope 
    - queue
    - videoconvert 
    - x264enc 
    - flvmux streamable=true 
    - queue
    - rtmpsink location="rtmp://localhost:1935/live/audio_test"
