# replace - with !, then use `gst-launch-1.0 $pipeline`
pipelines:
  pipeline_test:
    - videotestsrc num-buffers=100
    - capsfilter caps="video/x-raw, width=1920, height=1080, framerate=30/1"
    - autovideosink

  mac_capture_screen:
    - avfvideosrc capture-screen=true 
    - videoscale 
    - videoconvert 
    - capsfilter caps="ideo/x-raw,width=640,height=480"
    - osxvideosink

  rtmp_test:
    - videotestsrc 
    - clockoverlay 
    - queue 
    - videoconvert 
    - x264enc speed-preset=5 tune=4
    - flvmux streamable=true 
    - rtmpsink location=rtmp://localhost:1935/live/waltertest

  video_test:
    - v4l2src device=/dev/video0
    - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
    - nvvideoconvert
    - videorate max-rate=30
    - nvv4l2h264enc
    - h264parse
    - flvmux streamable=true
    - rtmpsink location=rtmp://localhost:1935/live/waltertest

  audio_test:
    - alsasrc device=hw:3,0 
    - audioconvert 
    - wavescope 
    - queue name=q1 
    - videoconvert 
    - x264enc 
    - flvmux streamable=true 
    - queue  name=q2
    - rtmpsink location="rtmp://localhost:1935/live/wavetest"

logger:
  log_level: 3
  log_console: 0