general:
  default_pipeline: mp4_play
  log_folder: ./log
  log_name: pipeline_verify
  # log level - 0:trace, 1: debug, 2: info ...
  log_level: 1
  # gstreamer log level - GST_LEVEL_FIXME=3,GST_LEVEL_INFO=4,..
  debug_threshold: 3 
  http_port: 9988
  web_root: ./doc
pipelines:
  pipeline_test:
    - videotestsrc num-buffers=100
    - capsfilter caps="video/x-raw, width=1920, height=1080, framerate=30/1"
    - autovideosink

  mic_test:
    - autoaudiosrc
    - audioconvert
    - wavescope
    - videoconvert
    - autovideosink

  rtmp_test:    
    - filesrc location=material/talk.mp4
    - decodebin
    - videoconvert 
    - identity drop-allocation=1
    - openh264enc bitrate=4000000
    - videoconvert
    - flvmux streamable=true
    - rtmpsink location='rtmp://192.168.104.199:1935/live/talktest'

  mp4_play:
    - filesrc location=./material/talk.mp4 
    - decodebin name=dec
    - videoconvert 
    - timeoverlay 
    - autovideosink dec. 
    - audioconvert 
    - audioresample 
    - autoaudiosink

  videojpg2rtmp:
    - v4l2src device=/dev/video1
    - capsfilter caps="image/jpeg,width=1920, height=1080, framerate=30/1"
    - nvv4l2decoder mjpeg=1
    - nvvideoconvert
    - videorate max-rate=30
    - nvv4l2h264enc
    - h264parse
    - flvmux streamable=true
    - rtmpsink location=rtmp://localhost:1935/live/video_test

  videoxraw2rtmp:
    - v4l2src device=/dev/video0
    - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
    - nvvideoconvert
    - videorate max-rate=30
    - nvv4l2h264enc
    - h264parse
    - flvmux streamable=true
    - rtmpsink location=rtmp://localhost:1935/live/video_test

  audio2rtmp:
    - alsasrc device=hw:3,0 
    - audioconvert 
    - wavescope 
    - queue
    - videoconvert 
    - x264enc 
    - flvmux streamable=true 
    - queue
    - rtmpsink location="rtmp://localhost:1935/live/audio_test"
# refer to https://gstreamer.freedesktop.org/documentation/additional/design/probes.html
probes:
  mp4_play_probe:
    probe_pipeline: mp4_play
    probe_element: timeoverlay
    probe_pad: src 
    #GST_PAD_PROBE_TYPE_ALL_BOTH (1776) – probe buffers
    probe_type: 1776