# replace - with !, then use `gst-launch-1.0 $pipeline`
pipelines:
  pipeline_jetson:
    - v4l2src
    - capsfilter
    - nvv4l2decoder
    - nvvideoconvert
    - nvv4l2h264enc
    - rtph264pay
    - capsfilter
    - webrtcbin

  pipeline_mp4_rtmp:
    - filesrc location=material/talk.mp4 
    - decodebin 
    - videoconvert 
    - identity drop-allocation=1 
    - x264enc speed-preset=5 tune=4 byte-stream=true threads=1 key-int-max=15 intra-refresh=true
    - flvmux streamable=true
    - rtmpsink location="rtmp://localhost:1935/live/waltertest"

  pipeline_rtp_sender:
    - v4l2src device=/dev/video1
    - decodebin
    - videoconvert 
    - omxh264enc video/x-h264,stream-format=byte-stream
    - rtph264pay 
    - udpsink host=localhost port=5000

  pipeline_rtp_receiver:
    - udpsrc  port=5000 caps=application/x-rtp
    - rtph264depay
    - avdec_h264
    - autovideosink

  pipeline_test:
    - videotestsrc num-buffers=100
    - capsfilter caps="video/x-raw, width=1920, height=1080, framerate=30/1"
    - autovideosink

  mac_capture_screen:
    - avfvideosrc capture-screen=true 
    - videoscale 
    - videoconvert 
    - capsfilter caps="ideo/x-raw,width=640,height=480"
    - osxvideosink

  pipeline_test_rtmp:
    - videotestsrc 
    - clockoverlay 
    - queue 
    - videoconvert 
    - x264enc speed-preset=5 tune=4
    - flvmux streamable=true 
    - rtmpsink location=rtmp://localhost:1935/live/waltertest

  pipeline_test_pcm:
    - filesrc location=material/16k16bit.pcm
    - capsfilter caps="audio/x-raw,format=S16LE,channels=1,rate=16000,layout=interleaved"
    - audioconvert 
    - audioresample 
    - autoaudiosink

  pipeline_record_wav:
    - osxaudiosrc
    - audioconvert 
    - audioresample
    - capsfilter caps="audio/x-raw,format=S16LE,channels=1,rate=16000,layout=interleaved"
    - tee
    - queue name=record_queue
    - splitmuxsink location=test_%5d.wav muxer=wavenc
    - tee
    - queue name=visual_queue
    - wavescope
    - videoconvert
    - autovideosink
logger:
  log_level: 3
  log_console: 0