pipelines:
  camera_to_mp4:
    desc: capture camera's video to mp4
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video0 num-buffers=100
      - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
      - nvvideoconvert
      - videorate max-rate=30
      - nvv4l2h264enc
      - h264parse
      - mp4mux
      - filesink location=test.mp4

  camera_to_rtmp:
    desc: capture camera's video and push via rtmp
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video0
      - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
      - nvvideoconvert
      - videorate max-rate=30
      - nvv4l2h264enc
      - h264parse
      - flvmux streamable=true
      - rtmpsink location=rtmp://localhost:1935/live/waltertest

  video_rate_test:
    desc: capture video, change video rate and push via rtmp
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video0
      - capsfilter caps="video/x-raw,width=1920, height=1080, framerate=60/1"
      - nvvideoconvert
      - capsfilter caps="video/x-raw(memory:NVMM),width=1920,height=1080, framerate=60/1"
      - videorate max-rate=30
      - nvv4l2h264enc maxperf-enable=1 control-rate=1 capture-io-mode=2 output-io-mode=5 insert-sps-pps=1 bitrate=2000000
      - h264parse
      - flvmux streamable=true
      - rtmpsink location=rtmp://localhost:1935/live/waltertest

  video_display:
    desc: capture video, change video rate and display
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video0
      - capsfilter caps="video/x-raw,width=1920,height=1080, framerate=60/1"
      - nvvideoconvert
      - capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=1920,height=1080, framerate=60/1"
      - queue
      - videorate max-rate=30
      - nvvideoconvert
      - capsfilter caps="video/x-raw(memory:NVMM),width=1920,height=1080, framerate=30/1"
      - nvoverlaysink sync=0

  video_jpeg:
    desc: capture video as image/jpeg format, then display it
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video1
      - capsfilter caps="image/jpeg,width=1920,height=1080"
      - nvv4l2decoder mjpeg=1
      - nvvideoconvert
      - xvimagesink sync=0

  video_xraw:
    desc: capture video as video/x-raw format, then display it
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video0
      - capsfilter caps="video/x-raw,width=1920,height=1080"
      - nvvideoconvert
      - xvimagesink sync=0

  video_record:
    desc: record video from camera
    tags: video, jetson, nvidia
    steps:
      - v4l2src device=/dev/video1
      - capsfilter caps="image/jpeg,width=1920,height=1080,framerate=30/1"
      - nvv4l2decoder mjpeg=1
      - nvvideoconvert
      - capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=1920,height=1080,framerate=30/1"
      - tee name=t t.
      - queue
      - nvv4l2h264enc
      - h264parse
      - hlssink2 max-files=10 location=/tmp/hls_record_%03d.ts playlist-location=/tmp/hls_playlist.m3u8 target-duration=10 t.
      - queue
      - autovideosink

  ds_example_1:
    desc: deep stream example 1
    tags: jetson
    steps:
      - filesrc location=/opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.h264
      - h264parse
      - nvv4l2decoder
      - nvstreammux0.sink_0 nvstreammux batch-size=1 width=1920 height=1080 batched-push-timeout=40000
      - nvinfer config-file-path=/opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test1/dstest1_pgie_config.txt
      - nvvideoconvert
      - nvdsosd
      - autovideosink

