# replace - with !, then use `gst-launch-1.0 $pipeline`
pipelines:
  pipeline_mp4_rtmp:
    - filesrc location=material/talk.mp4 
    - decodebin 
    - videoconvert 
    - identity drop-allocation=1 
    - x264enc speed-preset=5 tune=4 byte-stream=true threads=1 key-int-max=15 intra-refresh=true
    - flvmux streamable=true
    - rtmpsink location="rtmp://localhost:1935/live/waltertest"

  pipeline_rtp_sender:
    - v4l2src device=/dev/video1
    - decodebin
    - videoconvert 
    - omxh264enc video/x-h264,stream-format=byte-stream
    - rtph264pay 
    - udpsink host=localhost port=5000

  pipeline_rtp_receiver:
    - udpsrc  port=5000 caps=application/x-rtp
    - rtph264depay
    - avdec_h264
    - autovideosink

  pipeline_test:
    - videotestsrc num-buffers=100
    - capsfilter caps="video/x-raw, width=1920, height=1080, framerate=30/1"
    - autovideosink

  mac_capture_screen:
    - avfvideosrc capture-screen=true 
    - videoscale 
    - videoconvert 
    - capsfilter caps="ideo/x-raw,width=640,height=480"
    - osxvideosink

  pipeline_test_rtmp:
    - videotestsrc 
    - clockoverlay 
    - queue 
    - videoconvert 
    - x264enc speed-preset=5 tune=4
    - flvmux streamable=true 
    - rtmpsink location=rtmp://localhost:1935/live/waltertest


logger:
  log_level: 3
  log_console: 0