pipelines:
  h264_decode:
    desc: decode mp4 with h264 and play it
    tags: video
    steps:
      - filesrc location=filename.mp4
      - qtdemux name=demux demux.video_0
      - queue
      - h264parse
      - openh264dec
      - autovideosink

  h265_decode:
    desc: decode mp4 with h265 and play it
    tags: video
    steps:
      - filesrc location=filename.mp4
      - qtdemux name=demux demux.video_0
      - queue
      - h265parse
      - avdec_h265
      - autovideosink

  pipeline_mp4_rtmp:
    desc: push mp4 via rtmp
    tags: video
    steps:
      - filesrc location=material/talk.mp4
      - decodebin
      - videoconvert
      - identity drop-allocation=1
      - x264enc speed-preset=5 tune=4 byte-stream=true threads=1 key-int-max=15 intra-refresh=true
      - flvmux streamable=true
      - rtmpsink location="rtmp://localhost:1935/live/waltertest"

  pipeline_rtp_sender:
    desc: send camera's video via rtp
    tags: video, linux
    steps:
      - v4l2src device=/dev/video1
      - decodebin
      - videoconvert
      - omxh264enc video/x-h264,stream-format=byte-stream
      - rtph264pay
      - udpsink host=localhost port=5000

  pipeline_rtp_receiver:
    desc: receive camera's video via rtp
    tags: video
    steps:
      - udpsrc  port=5000 caps=application/x-rtp
      - rtph264depay
      - avdec_h264
      - autovideosink

  pipeline_test:
    desc: playback test video
    tags: video
    steps:
      - videotestsrc num-buffers=100
      - capsfilter caps="video/x-raw, width=1920, height=1080, framerate=30/1"
      - autovideosink

  pipeline_test_rtmp:
    desc: push test video via rtmp
    tags: video
    steps:
      - videotestsrc
      - clockoverlay
      - queue
      - videoconvert
      - x264enc speed-preset=5 tune=4
      - flvmux streamable=true
      - rtmpsink location=rtmp://localhost:1935/live/waltertest

  recod2flv:
    desc: record test video to flv
    tags: video
    steps:
      - videotestsrc num-buffers=60
      - x264enc
      - flvmux
      - filesink location=abc.flv

  record2mp4:
    desc: record test video to mp4
    tags: video
    steps:
      - videotestsrc num-buffers=60
      - timeoverlay
      - x264enc
      - qtmux
      - filesink location=abc.mp4

  record2hls:
    desc: record test video to hls
    tags: video
    steps:
      - videotestsrc is-live=true num-buffers=100
      - identity
      - timeoverlay
      - x264enc
      - h264parse
      - hlssink2 max-files=10 location=/tmp/hls_record_%03d.ts playlist-location=/tmp/hls_playlist.m3u8 target-duration=10

  record_mp4_display:
    desc: record test video to mp4
    tags: video
    steps:
      - videotestsrc is-live=true num-buffers=100
      - timeoverlay
      - tee name=t t.
      - queue leaky=1
      - x264enc
      - mp4mux
      - filesink location=xyz.mp4 t.
      - queue leaky=1
      - autovideosink sync=false

  hls2mp4:
    desc: convert hls to mp4
    tags: video
    steps:
      - filesrc location=material/snapshot_20240227151256.m3u8
      - hlsdemux
      - filesink location=snapshot_20240227151256.mp4

  hlsplay:
    desc: playback hls file
    tags: video, hls
    steps:
      - filesrc location="/tmp/hls_playlist.m3u8"
      - hlsdemux
      - decodebin
      - videoconvert
      - videoscale
      - autovideosink

  tsplay:
    desc: playback mpeg ts file
    tags: video, hls
    steps:
      - filesrc location="material/record_20240229135840_00012.ts"
      - tsdemux
      - decodebin
      - videoconvert
      - autovideosink
